FROM mysql:8.0

# Set the desired directories
ENV MYSQL_LOG_DIR /var/log/mysql
ENV MYSQL_DATA_DIR /var/lib/mysql

# Create and set permissions for log and data directories
RUN if [ ! -d "$MYSQL_LOG_DIR" ]; then mkdir -p "$MYSQL_LOG_DIR"; fi
RUN chown -R mysql:mysql "$MYSQL_LOG_DIR" && chmod 755 "$MYSQL_LOG_DIR"

RUN if [ ! -d "$MYSQL_DATA_DIR" ]; then mkdir -p "$MYSQL_DATA_DIR"; fi
RUN chown -R mysql:mysql "$MYSQL_DATA_DIR" && chmod 700 "$MYSQL_DATA_DIR"

COPY my.cnf /etc/mysql/conf.d/
RUN chmod 644 /etc/mysql/conf.d/my.cnf

COPY ./scripts/ /docker-entrypoint-initdb.d/

# Set timezone
ENV TZ=America/Edmonton

HEALTHCHECK CMD mysqladmin ping -h localhost
